#!/usr/bin/env python

# Run as node-exporter user from cron (assuming you have open access to nginx logs):
#    */5 * * * * node-exporter /path/to/runner nginxmon

import glob
import re

if __name__ == '__main__':
  nginx_method_count = {}
  nginx_response_code_count = {}
  nginx_sent_bytes = {}

  logre = re.compile('[^ ]+ [^ ]+ [^ ]+ \[[^]]+\] "([A-Z]+) [^"]+" ([0-9]+) ([0-9]+) "[^"]+" "[^"]+"')
  for log in glob.glob('/var/log/nginx/*_access.log'):
    m = re.match('/var/log/nginx/(.*)_access.log', log)
    site = m.groups()[0]
    nginx_method_count[site] = {}
    nginx_response_code_count[site] = {}
    nginx_sent_bytes[site] = 0
    with open(log, 'r') as lf:
      for logline in lf:
        m = logre.match(logline)
        if m:
          method = m.groups()[0]
          response_code = int(m.groups()[1])
          bytes_sent = int(m.groups()[2])
          nginx_method_count[site][method
            ] = nginx_method_count[site].setdefault(method, 0) + 1
          nginx_response_code_count[site][response_code
            ] = nginx_response_code_count[site].setdefault(response_code, 0) + 1
          nginx_sent_bytes[site] += bytes_sent

  print '# TYPE nginx_method_count counter'
  for site, methods in nginx_method_count.items():
    for method, count in nginx_method_count[site].items():
      print 'nginx_method_count{site="%s",method="%s"} %d' % (site, method, count)

  print '# TYPE nginx_response_code_count counter'
  for site, response_codes in nginx_response_code_count.items():
    for response_code, count in nginx_response_code_count[site].items():
      print 'nginx_response_code_count{site="%s",response_code="%s"} %d' % (
                                                              site, response_code, count)

  print '# TYPE nginx_sent_bytes counter'
  for site, bytes_sent in nginx_sent_bytes.items():
    print 'nginx_sent_bytes{site="%s"} %d' % (site, bytes_sent)
